# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  eventsourcing-bbl-benchmarks:
    dependencies:
    - base
    - eventsourcing-bbl
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: eventsourcing-bbl is a new Haskeleton package.
executables:
  bbl-game:
    dependencies:
    - base
    - eventsourcing-bbl
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: YoEight/eventsourcing-bbl
library:
  dependencies:
  - base
  - ansi-terminal
  - lens
  - mtl
  - vty
  - vector
  - eventsource-api
  - eventsource-geteventstore-store
  - aeson
  - eventstore
  source-dirs: library
license: MIT
maintainer: Yorick Laupa
name: eventsourcing-bbl
synopsis: A new Haskeleton package.
default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NoImplicitPrelude
  - TypeFamilies
  - FlexibleContexts
dependencies:
  - classy-prelude
tests:
  eventsourcing-bbl-test-suite:
    dependencies:
    - base
    - eventsourcing-bbl
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
